FROM indraniel/python3-tools@sha256:db9eac6a644e3fdd17d77670061daf40b6a64fea38a04027f327606003539744
LABEL maintainer "Allison Regier <aregier@wustl.edu>"

RUN mkdir -p /opt/hall-lab
ADD customize_notebook.py /opt/hall-lab

CMD ["/bin/bash"]
